data:
  testdata_path: "./data/test_dataset.csv"
  traindata_path: "./data/train_dataset.csv"
  data_dim: 6 # 36维特征转换为 6*6 的初始输入
---
model:
  lstm_dim: 200
  fc1_dim: 100
  fc2_dim: 2

---
train:
  batch_size: 32
  checkpoint_interval: 1000
  num_workers: 2 # 工作的线程数
  epoches: 1000 # 遍历训练集全集的次数
  adam: 0.001
  chkpt: 10 # 做一次chkpt的间隔数

---
test:
  batch_size: 32
  num_workers: 2 # 工作的线程数

---
log:
  chkpt_dir: './chkpt'
  log_dir: './logs'

